/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Container.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GlobalAcceptButton: typeof import('./src/components/global/AcceptButton.vue')['default']
    IconsBrackets: typeof import('./src/components/icons/Brackets.vue')['default']
    IconsGithub: typeof import('./src/components/icons/Github.vue')['default']
    IconsLinkedin: typeof import('./src/components/icons/Linkedin.vue')['default']
    IconsMail: typeof import('./src/components/icons/Mail.vue')['default']
    IconsMoon: typeof import('./src/components/icons/Moon.vue')['default']
    IconsPDF: typeof import('./src/components/icons/PDF.vue')['default']
    IconsSun: typeof import('./src/components/icons/Sun.vue')['default']
    IconsTag: typeof import('./src/components/icons/Tag.vue')['default']
    IconsUserAvatar: typeof import('./src/components/icons/UserAvatar.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
